#!/bin/bash

# If not running interactively, don't do anything
[[ -z "$PS1" ]] && return
[[ -f "$HOME/.force_zsh" ]] && exec zsh && return

for f in $(find ~/.shell/ -name '*.bash'); do source $f; done

source $HOME/.shell/common.sh
common.is_already_sourced bashrc && return || SOURCE+=("bashrc")
common.export_shell
[[ ! "$SHELL" =~ bash ]] && return
common.source_all

# Set prompt
if [[ $(basename ${BASH_SOURCE[0]}) == ".bashrc" ]]; then
    source ~/.shell/bash/default.sh
    source ~/.shell/bash/prompt.sh
    PS1='# '
    PROMPT_COMMAND=prompt.display
fi
