export PATH="$HOME/.local/bin:/usr/local/bin:$PATH"

if [[ ! -f ~/.zpm/zpm.zsh ]]; then
  git clone --recursive https://github.com/jcosmao/zpm ~/.zpm
fi
source ~/.zpm/zpm.zsh

ZPM_PLUGINS=~/.zpm/plugins/jcosmao---

zpm load jcosmao/myzsh
zpm load jcosmao/zsh-completions
zpm load jcosmao/zsh-syntax-highlighting,apply:fpath
for f in $(find ${ZPM_PLUGINS}myzsh/ -name '*.zsh'); do source $f; done
for f in $(find ~/.shell/ -name '*.zsh'); do source $f; done
zpm load jcosmao/zsh-bash-completions-fallback
zpm load jcosmao/blox-zsh-theme
source ${ZPM_PLUGINS}blox-zsh-theme/blox.zsh
source ${ZPM_PLUGINS}zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
