# Load Antigen
source ~/.shell/antigen.zsh

export SHELL='zsh'

# Load various lib files
antigen use oh-my-zsh

# Plugins
#antigen bundle git
antigen bundle wd
antigen bundle pip
antigen bundle python
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle jcosmao/blox-zsh-theme
source ~/.shell/plugins/theme.zsh

# Apply after override theme variables
antigen apply

autoload -U +X compinit && compinit
autoload -U +X bashcompinit && bashcompinit
source ~/.shell/plugins/zsh-bash.zsh

# ssh-agent ~/.bash/functions
if declare -f launch_ssh_agent &> /dev/null; then
    launch_ssh_agent
fi

# Auto reload completion
zstyle ":completion:*:commands" rehash 1

# if we SSH then autolaunch default tmux session
#if [[ -n $SSH_TTY && -z $TMUX ]]; then
#    tm default
#fi
