# Load Antigen
source ~/.shell/antigen.zsh

export SHELL='zsh'

# Plugins
antigen use oh-my-zsh

antigen bundle mfaerevaag/wd
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zdharma/fast-syntax-highlighting
antigen bundle jcosmao/blox-zsh-theme
source ~/.shell/plugins/theme.zsh

# Apply after override theme variables
antigen apply

autoload -U +X compinit && compinit
autoload -U +X bashcompinit && bashcompinit
source ~/.shell/plugins/zsh-bash.zsh
source ~/.shell/completions/completion.source
source ~/.shell/completions/tm.completion.source

# ssh-agent ~/.bash/functions
if declare -f launch_ssh_agent &> /dev/null; then
    launch_ssh_agent
fi

# Auto reload completion
zstyle ":completion:*:commands" rehash true

# if we SSH then autolaunch default tmux session
#if [[ -n $SSH_TTY && -z $TMUX ]]; then
#    tm default
#fi
