#!/bin/bash

repo=$(basename -s .git $(git config --get remote.origin.url 2> /dev/null))

if [[ $repo == "dotfiles" ]]; then
    echo "[$0] Reset changes on webex.desktop / bashrc"

    {
        git reset ~/.dotfiles/config.X11/applications/webex.desktop
        git checkout -- ~/.dotfiles/config.X11/applications/webex.desktop
        git reset ~/.dotfiles/shell/bashrc
        git checkout -- ~/.dotfiles/shell/bashrc
    } 2>&1 > /dev/null
fi
