return {
    'MeanderingProgrammer/render-markdown.nvim',
    ft = { "markdown", "norg", "rmd", "org" },
    opts = {
        heading = {
            enabled = true,
            sign = true,
            position = 'overlay',
            icons = { '󰎤 ', '󰎩 ', '󰲤 ', '󰲧 ', '󰼓 ' },
            signs = { '󰫎 ' },
            width = 'block',
            left_margin = 1,
            left_pad = 1,
            right_pad = 0,
            min_width = 120,
            border = false,
            border_virtual = true,
            border_prefix = true,
            backgrounds = {
                'RenderMarkdownH1Bg',
                'RenderMarkdownH2Bg',
                'RenderMarkdownH3Bg',
                'RenderMarkdownH4Bg',
                'RenderMarkdownH5Bg',
                'RenderMarkdownH6Bg',
            },
            foregrounds = {
                'RenderMarkdownH1',
                'RenderMarkdownH2',
                'RenderMarkdownH3',
                'RenderMarkdownH4',
                'RenderMarkdownH5',
                'RenderMarkdownH6',
            },
        },
        code = {
            enabled = true,
            sign = true,
            position = 'right',
            right_pad = 10,
            language_name = true,
            width = 'block',
            min_width = 118,
            border = 'thick',
            left_margin = 2,
            left_pad = 2,
        },
    }
}
