#!/bin/bash

label=''
color_up='#FF7961'
color_down='#676767'

function wireguard_iface {
    ip --json link show | jq -r '.[] | select(.ifname | test("^wg")).ifname' | head -1
}

function protonvpn_iface {
    ip --json link show | jq -r '.[] | select(.ifname | test("^proton")).ifname' | head -1
}

if [[ -f /var/run/vpnc.pid || -n $(pidof nm-vpnc-service) || -n $(wireguard_iface) || -n $(protonvpn_iface) ]]; then
    [[ -n $(wireguard_iface) ]] && iface=$(wireguard_iface)
    [[ -n $(protonvpn_iface) ]] && iface=$(protonvpn_iface)
    echo "$label  $iface"
    echo $label
    echo $color_up
else
    echo $label
    echo $label
    echo $color_down
fi
