# Load Antigen
source ~/.zsh/antigen.zsh

# Load various lib files
antigen use oh-my-zsh

# Plugins
#antigen bundle git
antigen bundle wd
antigen bundle pip
antigen bundle python
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle jcosmao/blox-zsh-theme
antigen apply

autoload -U +X compinit && compinit
autoload -U +X bashcompinit && bashcompinit

# Auto reload completion
zstyle ":completion:*:commands" rehash 1

source ~/.zsh/plugins/zsh-bash.zsh
source ~/.zsh/plugins/theme.zsh

# ssh-agent ~/.bash/functions
if declare -f launch_ssh_agent &> /dev/null; then
    launch_ssh_agent
fi

# fuzzysearch
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git --exclude .pyc --exclude __pycache__'
export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border'
