# Load Antigen
source ~/.zsh/antigen.zsh

# Load various lib files
antigen use oh-my-zsh

# Plugins
#antigen bundle git
antigen bundle wd
antigen bundle pip
antigen bundle python
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle jcosmao/blox-zsh-theme
antigen apply

source ~/.zsh/plugins/zsh-bash.plugin.zsh
source ~/.zsh/plugins/blox_theme.zsh

# enable color support
autoload -Uz colors && colors
if [ -x /usr/bin/dircolors ]; then
    alias ls='ls --color=auto'
    eval "`dircolors -b`"
fi

# source bash aliases/functions
[[ -e ~/.bash_aliases ]] && source ~/.bash_aliases

if [[ -e ~/.bash ]]; then
    for source in $(find ~/.bash -type f -name '*.source' )
    do
        . $source
    done
fi

# Not versionned
if [[ -e ~/.bash_custom ]]; then
    for source in $(find ~/.bash_custom -type f -name '*.source' )
    do
        . $source
    done
fi

# ssh-agent ~/.bash/functions
launch_ssh_agent
